# behave.ini
[behave.userdata]
# choose from "chromium", "firefox" or "webkit"
browser = chromium

# headless=true/false
headless = false

# your app’s base URL
#base_url = https://staging.example.com
